In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset0 = pd.read_csv("09_Nasapower_Climate_Monthly_Mersin_FinalVersion.csv",index_col=0)

In [3]:
dataset0 = dataset0.reset_index()
dataset0['Tarih'] = pd.to_datetime(dataset0['Tarih'], errors='coerce')
dataset0.set_index('Tarih', inplace=True)

In [4]:
dataset0["Drought_Class"].unique()

array(['Extremely Wet', 'Severely Wet', 'Normal', 'Moderately Dry',
       'Moderately Wet'], dtype=object)

In [5]:
dataset0.head()

2m Bağıl Nem (%)  2m Hava Sıcaklığı(°C)  2m Rüzgâr Hızı (m/s)  \
Tarih                                                                       
1981-01-15             82.24                   1.32                  3.50   
1981-02-15             83.43                   1.11                  2.46   
1981-03-15             76.62                   5.94                  2.54   
1981-04-15             66.20                   8.70                  2.03   
1981-05-15             61.53                  12.27                  2.15   

            Küresel Güneş Radyasyonu (MJ/m2/gün)  Toplam Yağış Miktarı (mm)  \
Tarih                                                                         
1981-01-15                                  7.75                     174.17   
1981-02-15                                 11.20                      88.69   
1981-03-15                                 15.57                      24.21   
1981-04-15                                 18.91                      26.42   
1981-05-15                                 22.75                      26.41   

            Tmax_at 2 Meters(°C)  Tmin_at 2 Meters(°C)  J(Day of Year)  \
Tarih                                                                    
1981-01-15                 14.37                  0.40              15   
1981-02-15                 16.37                  1.25              46   
1981-03-15                 22.62                  3.47              74   
1981-04-15                 29.12                  2.41             105   
1981-05-15                 36.76                  7.65             135   

            ET0_FAO56_mm  Water_Balance_mm    SPEI_1  Drought_Class  
Tarih                                                                
1981-01-15      1.097203        173.072797  4.331873  Extremely Wet  
1981-02-15      1.256133         87.433867  1.745743   Severely Wet  
1981-03-15      2.348252         21.861748 -0.234408         Normal  
1981-04-15      3.664460         22.755540 -0.207417         Normal  
1981-05-15      5.601238         20.808762 -0.266206         Normal

In [6]:
#dataset0['Next Month'] = df['Durum'].shift(-1)

In [7]:
sequent_mapping = {
    'Moderately Dry': 0,
    'Normal': 1,
    'Moderately Wet': 2,
    'Severely Wet': 3,
    'Extremely Wet': 4
}

In [8]:
dataset0['Encoded_Target'] = dataset0['Drought_Class'].map(sequent_mapping)

In [9]:
dataset0.head()

2m Bağıl Nem (%)  2m Hava Sıcaklığı(°C)  2m Rüzgâr Hızı (m/s)  \
Tarih                                                                       
1981-01-15             82.24                   1.32                  3.50   
1981-02-15             83.43                   1.11                  2.46   
1981-03-15             76.62                   5.94                  2.54   
1981-04-15             66.20                   8.70                  2.03   
1981-05-15             61.53                  12.27                  2.15   

            Küresel Güneş Radyasyonu (MJ/m2/gün)  Toplam Yağış Miktarı (mm)  \
Tarih                                                                         
1981-01-15                                  7.75                     174.17   
1981-02-15                                 11.20                      88.69   
1981-03-15                                 15.57                      24.21   
1981-04-15                                 18.91                      26.42   
1981-05-15                                 22.75                      26.41   

            Tmax_at 2 Meters(°C)  Tmin_at 2 Meters(°C)  J(Day of Year)  \
Tarih                                                                    
1981-01-15                 14.37                  0.40              15   
1981-02-15                 16.37                  1.25              46   
1981-03-15                 22.62                  3.47              74   
1981-04-15                 29.12                  2.41             105   
1981-05-15                 36.76                  7.65             135   

            ET0_FAO56_mm  Water_Balance_mm    SPEI_1  Drought_Class  \
Tarih                                                                 
1981-01-15      1.097203        173.072797  4.331873  Extremely Wet   
1981-02-15      1.256133         87.433867  1.745743   Severely Wet   
1981-03-15      2.348252         21.861748 -0.234408         Normal   
1981-04-15      3.664460         22.755540 -0.207417         Normal   
1981-05-15      5.601238         20.808762 -0.266206         Normal   

            Encoded_Target  
Tarih                       
1981-01-15               4  
1981-02-15               3  
1981-03-15               1  
1981-04-15               1  
1981-05-15               1

In [10]:
dataset1=dataset0.drop("Drought_Class",axis=1)

In [11]:
dataset1.head()

2m Bağıl Nem (%)  2m Hava Sıcaklığı(°C)  2m Rüzgâr Hızı (m/s)  \
Tarih                                                                       
1981-01-15             82.24                   1.32                  3.50   
1981-02-15             83.43                   1.11                  2.46   
1981-03-15             76.62                   5.94                  2.54   
1981-04-15             66.20                   8.70                  2.03   
1981-05-15             61.53                  12.27                  2.15   

            Küresel Güneş Radyasyonu (MJ/m2/gün)  Toplam Yağış Miktarı (mm)  \
Tarih                                                                         
1981-01-15                                  7.75                     174.17   
1981-02-15                                 11.20                      88.69   
1981-03-15                                 15.57                      24.21   
1981-04-15                                 18.91                      26.42   
1981-05-15                                 22.75                      26.41   

            Tmax_at 2 Meters(°C)  Tmin_at 2 Meters(°C)  J(Day of Year)  \
Tarih                                                                    
1981-01-15                 14.37                  0.40              15   
1981-02-15                 16.37                  1.25              46   
1981-03-15                 22.62                  3.47              74   
1981-04-15                 29.12                  2.41             105   
1981-05-15                 36.76                  7.65             135   

            ET0_FAO56_mm  Water_Balance_mm    SPEI_1  Encoded_Target  
Tarih                                                                 
1981-01-15      1.097203        173.072797  4.331873               4  
1981-02-15      1.256133         87.433867  1.745743               3  
1981-03-15      2.348252         21.861748 -0.234408               1  
1981-04-15      3.664460         22.755540 -0.207417               1  
1981-05-15      5.601238         20.808762 -0.266206               1

In [12]:
dataset1['Next Month'] = dataset1['Encoded_Target'].shift(-1)

In [13]:
dataset1.tail()

2m Bağıl Nem (%)  2m Hava Sıcaklığı(°C)  2m Rüzgâr Hızı (m/s)  \
Tarih                                                                       
2025-08-15             31.23                  26.03                  2.09   
2025-09-15             39.16                  19.84                  2.13   
2025-10-15             14.06                  14.06                 14.06   
2025-11-15              9.39                   9.39                  9.39   
2025-12-15              7.03                   7.03                  7.03   

            Küresel Güneş Radyasyonu (MJ/m2/gün)  Toplam Yağış Miktarı (mm)  \
Tarih                                                                         
2025-08-15                                 22.98                       1.90   
2025-09-15                                 19.22                       3.19   
2025-10-15                                 14.06                      14.06   
2025-11-15                                  9.39                       9.39   
2025-12-15                                  7.03                       7.03   

            Tmax_at 2 Meters(°C)  Tmin_at 2 Meters(°C)  J(Day of Year)  \
Tarih                                                                    
2025-08-15                 47.23                 24.61             227   
2025-09-15                 39.93                 19.42             258   
2025-10-15                 33.35                 12.09             288   
2025-11-15                 10.84                 10.84             319   
2025-12-15                  5.57                  5.57             349   

            ET0_FAO56_mm  Water_Balance_mm    SPEI_1  Encoded_Target  \
Tarih                                                                  
2025-08-15      9.788980         -7.888980 -1.132822               0   
2025-09-15      7.239222         -4.049222 -1.016869               0   
2025-10-15     17.280205         -3.220205 -0.991834               1   
2025-11-15      6.718443          2.671557 -0.813914               1   
2025-12-15      4.432961          2.597039 -0.816165               1   

            Next Month  
Tarih                   
2025-08-15         0.0  
2025-09-15         1.0  
2025-10-15         1.0  
2025-11-15         1.0  
2025-12-15         NaN

In [14]:
#Gelecek ay hesabı için kaydırma yapmış oldum.

In [15]:
dataset2=dataset1.drop("Encoded_Target",axis=1)

In [16]:
dataset2.dropna(inplace=True)

In [17]:
dataset2['Next Month'] = dataset2['Next Month'].astype(int)

In [18]:
dataset2.tail()

2m Bağıl Nem (%)  2m Hava Sıcaklığı(°C)  2m Rüzgâr Hızı (m/s)  \
Tarih                                                                       
2025-07-15             30.49                  26.42                  2.15   
2025-08-15             31.23                  26.03                  2.09   
2025-09-15             39.16                  19.84                  2.13   
2025-10-15             14.06                  14.06                 14.06   
2025-11-15              9.39                   9.39                  9.39   

            Küresel Güneş Radyasyonu (MJ/m2/gün)  Toplam Yağış Miktarı (mm)  \
Tarih                                                                         
2025-07-15                                 23.16                       5.18   
2025-08-15                                 22.98                       1.90   
2025-09-15                                 19.22                       3.19   
2025-10-15                                 14.06                      14.06   
2025-11-15                                  9.39                       9.39   

            Tmax_at 2 Meters(°C)  Tmin_at 2 Meters(°C)  J(Day of Year)  \
Tarih                                                                    
2025-07-15                 45.68                 21.44             196   
2025-08-15                 47.23                 24.61             227   
2025-09-15                 39.93                 19.42             258   
2025-10-15                 33.35                 12.09             288   
2025-11-15                 10.84                 10.84             319   

            ET0_FAO56_mm  Water_Balance_mm    SPEI_1  Next Month  
Tarih                                                             
2025-07-15      9.405440         -4.225440 -1.022190           0  
2025-08-15      9.788980         -7.888980 -1.132822           0  
2025-09-15      7.239222         -4.049222 -1.016869           1  
2025-10-15     17.280205         -3.220205 -0.991834           1  
2025-11-15      6.718443          2.671557 -0.813914           1

In [19]:
dataset3 = dataset2.reset_index()

In [20]:
corr_matrix=dataset3.corr().abs()

In [21]:
corr_matrix

Tarih  2m Bağıl Nem (%)  \
Tarih                                 1.000000          0.074237   
2m Bağıl Nem (%)                      0.074237          1.000000   
2m Hava Sıcaklığı(°C)                 0.082615          0.920841   
2m Rüzgâr Hızı (m/s)                  0.036788          0.090898   
Küresel Güneş Radyasyonu (MJ/m2/gün)  0.085839          0.774967   
Toplam Yağış Miktarı (mm)             0.099509          0.736598   
Tmax_at 2 Meters(°C)                  0.067751          0.895964   
Tmin_at 2 Meters(°C)                  0.078946          0.908176   
J(Day of Year)                        0.017275          0.321469   
ET0_FAO56_mm                          0.071612          0.926610   
Water_Balance_mm                      0.099759          0.774181   
SPEI_1                                0.099759          0.774181   
Next Month                            0.077502          0.329642   

                                      2m Hava Sıcaklığı(°C)  \
Tarih                                              0.082615   
2m Bağıl Nem (%)                                   0.920841   
2m Hava Sıcaklığı(°C)                              1.000000   
2m Rüzgâr Hızı (m/s)                               0.050894   
Küresel Güneş Radyasyonu (MJ/m2/gün)               0.881885   
Toplam Yağış Miktarı (mm)                          0.639272   
Tmax_at 2 Meters(°C)                               0.969564   
Tmin_at 2 Meters(°C)                               0.973333   
J(Day of Year)                                     0.291060   
ET0_FAO56_mm                                       0.948046   
Water_Balance_mm                                   0.684855   
SPEI_1                                             0.684855   
Next Month                                         0.397635   

                                      2m Rüzgâr Hızı (m/s)  \
Tarih                                             0.036788   
2m Bağıl Nem (%)                                  0.090898   
2m Hava Sıcaklığı(°C)                             0.050894   
2m Rüzgâr Hızı (m/s)                              1.000000   
Küresel Güneş Radyasyonu (MJ/m2/gün)              0.032132   
Toplam Yağış Miktarı (mm)                         0.064032   
Tmax_at 2 Meters(°C)                              0.100262   
Tmin_at 2 Meters(°C)                              0.058808   
J(Day of Year)                                    0.100937   
ET0_FAO56_mm                                      0.161758   
Water_Balance_mm                                  0.045463   
SPEI_1                                            0.045463   
Next Month                                        0.051890   

                                      Küresel Güneş Radyasyonu (MJ/m2/gün)  \
Tarih                                                             0.085839   
2m Bağıl Nem (%)                                                  0.774967   
2m Hava Sıcaklığı(°C)                                             0.881885   
2m Rüzgâr Hızı (m/s)                                              0.032132   
Küresel Güneş Radyasyonu (MJ/m2/gün)                              1.000000   
Toplam Yağış Miktarı (mm)                                         0.626727   
Tmax_at 2 Meters(°C)                                              0.872228   
Tmin_at 2 Meters(°C)                                              0.822003   
J(Day of Year)                                                    0.045330   
ET0_FAO56_mm                                                      0.901835   
Water_Balance_mm                                                  0.668927   
SPEI_1                                                            0.668927   
Next Month                                                        0.527022   

                                      Toplam Yağış Miktarı (mm)  \
Tarih                                                  0.099509   
2m Bağıl Nem (%)                                       0.736598   
2m Hava Sıcaklığı(°C)                     

In [22]:
def drop_columns_Redundancy(dataset1, threshold):
    columns_drop = set()
    
    # DİKKAT: for döngüsü def bloğunun içine 4 boşlukla girmeli
    for i in range(len(corr_matrix.columns)):  
        # İç döngü de bir önceki for döngüsüne göre 4 boşlukla girmeli
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                # if bloğunun içi, if'e göre 4 boşlukla girmeli
                columns_drop.add(corr_matrix.columns[i])
                
    return columns_drop # return ifadesi de def bloğunun içinde olmalı
#set koleksiyonunu kullanmaz isem ortak sütünlar
#yüksek korelasyon içerdiğinden birdenn fazla aynı
#sütunu ekler.

In [23]:
dropped_columns=drop_columns_Redundancy(corr_matrix,0.90)

In [24]:
dropped_columns

{'2m Hava Sıcaklığı(°C)',
 'ET0_FAO56_mm',
 'SPEI_1',
 'Tmax_at 2 Meters(°C)',
 'Tmin_at 2 Meters(°C)',
 'Water_Balance_mm'}

In [25]:
X = dataset3.drop(['Tarih', 'Next Month','ET0_FAO56_mm','Water_Balance_mm'], axis=1)

In [26]:
y = dataset3['Next Month']

In [27]:
X.head()

2m Bağıl Nem (%)  2m Hava Sıcaklığı(°C)  2m Rüzgâr Hızı (m/s)  \
0             82.24                   1.32                  3.50   
1             83.43                   1.11                  2.46   
2             76.62                   5.94                  2.54   
3             66.20                   8.70                  2.03   
4             61.53                  12.27                  2.15   

   Küresel Güneş Radyasyonu (MJ/m2/gün)  Toplam Yağış Miktarı (mm)  \
0                                  7.75                     174.17   
1                                 11.20                      88.69   
2                                 15.57                      24.21   
3                                 18.91                      26.42   
4                                 22.75                      26.41   

   Tmax_at 2 Meters(°C)  Tmin_at 2 Meters(°C)  J(Day of Year)    SPEI_1  
0                 14.37                  0.40              15  4.331873  
1                 16.37                  1.25              46  1.745743  
2                 22.62                  3.47              74 -0.234408  
3                 29.12                  2.41             105 -0.207417  
4                 36.76                  7.65             135 -0.266206

In [28]:
#korelasyonlarada bakak yakın korelasyon varsa sileriz.

In [29]:
y.head()

0    3
1    1
2    1
3    1
4    1
Name: Next Month, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split

Eğer klasik Makine Öğrenmesi projelerindeki gibi veriyi karıştırırsanız (Shuffle), model "2025 yılının verisini görüp, 2024 yılını tahmin etmeye" çalışabilir.. Altın Kural: shuffle=False
Scikit-Learn kütüphanesindeki train_test_split fonksiyonunu kullanırken, shuffle (karıştırma) parametresini mutlaka False (Kapalı) yapmalısınız.

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
scaler=StandardScaler()

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size=0.20,  # Verinin son %20'si test olsun
    shuffle=False    # KESİNLİKLE FALSE OLMALI (Sırayı bozma)
)

In [34]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

In [60]:
LogReg = OneVsRestClassifier(LogisticRegression(solver='liblinear',class_weight='balanced'))

In [61]:
LogReg.fit(X_train_scaled, y_train)

OneVsRestClassifier(estimator=LogisticRegression(class_weight='balanced',
                                                 solver='liblinear'))

In [62]:
y_pred = LogReg.predict(X_test_scaled)

In [63]:
y_pred

array([4, 1, 1, 1, 1, 1, 0, 0, 0, 4, 4, 4, 3, 1, 1, 1, 1, 1, 0, 0, 0, 2,
       1, 4, 3, 1, 1, 1, 1, 0, 0, 0, 0, 2, 4, 4, 4, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 4, 4, 3, 1, 1, 1, 1, 0, 0, 0, 0, 1, 4, 4, 3, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 2, 4, 3, 1, 1, 1, 1, 1, 0, 0, 0, 4, 4, 4, 3, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 2, 4, 3, 1, 1, 1, 1, 0, 0, 0, 0, 4, 3, 3])

In [64]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [65]:
# 4. SONUÇLARI GÖR
print("Doğruluk (Accuracy):", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nDetaylı Rapor:\n", classification_report(y_test, y_pred))

Doğruluk (Accuracy): 0.5555555555555556

Confusion Matrix:
 [[15  3  0  0  0]
 [17 41  4  6 12]
 [ 0  1  0  0  3]
 [ 0  0  0  2  1]
 [ 0  0  0  1  2]]

Detaylı Rapor:
               precision    recall  f1-score   support

           0       0.47      0.83      0.60        18
           1       0.91      0.51      0.66        80
           2       0.00      0.00      0.00         4
           3       0.22      0.67      0.33         3
           4       0.11      0.67      0.19         3

    accuracy                           0.56       108
   macro avg       0.34      0.54      0.36       108
weighted avg       0.76      0.56      0.60       108



In [66]:
# 1. Hedef Değişkenleri Birleştir (Mapping)
# 3 ve 4'ü, 2'ye dönüştürüyoruz.
y_train_new = y_train.replace({3: 2, 4: 2})
y_test_new = y_test.replace({3: 2, 4: 2})

LogReg_New = OneVsRestClassifier(LogisticRegression(solver='liblinear', class_weight='balanced'))
LogReg_New.fit(X_train_scaled, y_train_new)


OneVsRestClassifier(estimator=LogisticRegression(class_weight='balanced',
                                                 solver='liblinear'))

In [67]:
y_pred_new = LogReg_New.predict(X_test_scaled)

print("YENİ DURUM (3 Sınıflı):")
print(classification_report(y_test_new, y_pred_new))

YENİ DURUM (3 Sınıflı):
              precision    recall  f1-score   support

           0       0.45      0.83      0.59        18
           1       0.91      0.54      0.68        80
           2       0.32      0.90      0.47        10

    accuracy                           0.62       108
   macro avg       0.56      0.76      0.58       108
weighted avg       0.78      0.62      0.64       108



In [69]:
#2025-12-01 Tarihi tahmini	çıktısı	

In [72]:
new_data={'2m Bağıl Nem (%)': [66.47],             # Örn: Biraz nemli
    '2m Hava Sıcaklığı(°C)': [13.07],        # Örn: Sıcak
    '2m Rüzgâr Hızı (m/s)': [1.24],          # Örn: Hafif rüzgar
    'Küresel Güneş Radyasyonu (MJ/m2/gün)': [10.29],
    'Toplam Yağış Miktarı (mm)': [0.3],   
    'Tmax_at 2 Meters(°C)': [18.19],
    'Tmin_at 2 Meters(°C)': [9.0],
    'J(Day of Year)': [335],                
    'SPEI_1': [-1.02]
         }

In [73]:
new_data1 = pd.DataFrame(new_data)
new_data2=scaler.transform(new_data1)

In [77]:
tahmin1_3=LogReg_New.predict(new_data2)
print("Tahmin Sonucu:", tahmin1_3)

Tahmin Sonucu: [2]


In [78]:
#3 değil 5 sınıfla çalışan modele atsak

In [80]:
tahmin2_4 = LogReg.predict(new_data2)
print("Tahmin Sonucu:", tahmin2_4)

Tahmin Sonucu: [3]


In [82]:
#hyperparametre tuning,artık ince ayarları biz yapıp model kuracağız.

In [83]:
model_advanced=OneVsRestClassifier(LogisticRegression())

In [84]:
penalty=[None,'l2','l1','elasticnet']
c_values=[100,10,1,0.1,0.01]
solver=['saga','lbfgs','newton-cg','newton-cg','newton-cholesky','sag']
class_weight = ['balanced', None]
max_iter = [100,1000,5000]
param_grid = {
    'solver': ['saga','lbfgs','newton-cg','newton-cg','newton-cholesky','sag'],       
    'C': [100,10,1,0.1,0.01],               
    'class_weight': ['balanced', None],     
    'penalty': [None,'l2','l1','elasticnet'],                     
    'max_iter': [100,1000,5000]                      
}

In [90]:
from sklearn.model_selection import GridSearchCV,TimeSeriesSplit

In [91]:
cv=TimeSeriesSplit()

In [ ]:
grid_modeli = GridSearchCV(
    estimator=LogisticRegression(),
    param_grid=parametreler,
    
    # KRİTİK DEĞİŞİKLİK BURADA:
    # cv=5 yerine cv=zaman_bolucusu yazıyoruz.
    cv=zaman_bolucusu,  
    
    scoring='f1_macro', # Dengesiz veri için f1 veya recall kullan
    n_jobs=-1,
    verbose=1
)